name: Deploy

on:
    push:
        branches: [ "develop" ]

jobs:
    web-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3
  
            - name: Set Up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20
            
            - name: Set Up Project
              run: |
                  cd HN.Management.Web/crezco-foundation &&
                  npm i &&
                  npm run build --if-present

            

